g2s_app_homepage:
    pattern:  /
    defaults: { _controller: G2sAppBundle:Home:index }

g2s_app_autocompletepage:
    pattern:  /autocomplete
    defaults: { _controller: G2sAppBundle:Autocomplete:index }